name: Publish app to production
run-name: Publish app to production
on: workflow_dispatch
jobs:
  Supervisely-Release:
    uses: supervisely-ecosystem/workflows/.github/workflows/common.yml@master
    secrets:
      SUPERVISELY_DEV_API_TOKEN: "${{ secrets.SUPERVISELY_DEV_API_TOKEN }}"
      SUPERVISELY_PRIVATE_DEV_API_TOKEN: "${{ secrets.SUPERVISELY_PRIVATE_DEV_API_TOKEN }}"
      SUPERVISELY_PROD_API_TOKEN: "${{ secrets.SUPERVISELY_PROD_API_TOKEN }}"
      GH_ACCESS_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    with:
      SUPERVISELY_SERVER_ADDRESS: "${{ vars.SUPERVISELY_PROD_SERVER_ADDRESS }}"
      SUPERVISELY_PROD_SERVER_ADDRESS: "${{ vars.SUPERVISELY_PROD_SERVER_ADDRESS }}"
      SLUG: "${{ github.repository }}"
      RELEASE_VERSION: ""
      RELEASE_DESCRIPTION: ""
      RELEASE_TYPE: "publish"
      SUBAPP_PATHS: "supervisely_integration/serve"